<?php

/**
 * @copyright Copyright © ${commentsYear} ${CommentsCompanyName}. All rights reserved.
 * @author    ${commentsUserEmail}
 */
?>
<?php
use Magento\Framework\View\Element\Template;
use ${Vendorname}\${Modulename}\ViewModel\${Actionname};
/** @var $viewModel ${Actionname} */
/** @var $block Template */
$viewModel = $block->getViewModel();
// Add your template code here. Use $viewModel for getting your data.
?>








