COMPONENT_NAME:=lingaro-magento2-codegen
COMPONENT:=lingaro/magento2-codegen
ENV_REPOSITORY:=

TARGET_PATH:=source/packages/$(COMPONENT_NAME)

MKTEMP:=mktemp -d
TMPDIR:=$(shell $(MKTEMP))
ARCHIVE:=$(TMPDIR)/archive.tar.gz
CP:=cp -R
RM:=rm -rf
TAR:=tar
GIT:=git
MKDIR=mkdir -p

.PHONY: all

all:
	$(info Running)
	$(info $(TMPDIR))

	$(TAR) -czvf $(ARCHIVE) .
	$(RM) ..?* .[!.]* *
	$(GIT) clone $(ENV_REPOSITORY) .
	$(MAKE) new \
		project=$(COMPONENT_NAME) \
		version=2.4.5-p1 \
		edition=community \
		static_cases=packages/$(COMPONENT_NAME) \
		unit_cases=packages/$(COMPONENT_NAME)/Test/Unit \
		integration_cases=packages/$(COMPONENT_NAME)/Test/Integration 
	$(MKDIR) $(TARGET_PATH)
	$(TAR) -xzvf $(ARCHIVE) -C $(TARGET_PATH)
	$(RM) $(TMPDIR)
	$(MAKE) run cmd="composer\ require\ $(COMPONENT)"