<?php
/*
 * @copyright Copyright © ${commentsYear} ${CommentsCompanyName}. All rights reserved.
 * @author    ${commentsUserEmail}
 */
?>
<?php
use Magento\Framework\View\Element\Template;
use ${Vendorname}\${Modulename}\ViewModel\${Viewmodel_name};
/** @var $viewModel ${Viewmodel_name} */
/** @var $block Template */
$viewModel = $block->getViewModel();
?>
<?php //@todo delete / replace this function with your implementation ?>
<h1><?php echo $block->escapeHtml($viewModel->getSampleText()); ?></h1>







