<?php
/*
 * @copyright Copyright © {{ commentsYear }} {{ commentsCompanyName }}. All rights reserved.
 * @author    {{ commentsUserEmail }}
 */
?>
<?php
use Magento\Framework\View\Element\Template;
use {{ vendorName }}\{{ moduleName }}\ViewModel\{{ viewModelName }};
/** @var $viewModel {{ viewModelName }} */
/** @var $block Template */
$viewModel = $block->getViewModel();
// Add your template code here. Use $viewModel for getting your data.
?>