{% if withTemplate == true %}
<?php

/**
 * @copyright Copyright © {{ commentsYear }} {{ commentsCompanyName|raw }}. All rights reserved.
 * @author    {{ commentsUserEmail }}
 */

declare(strict_types=1);

/** @var \{{ vendorName|pascal }}\{{ moduleName|pascal }}\Block\Widget\{{ name|pascal }} $block  */
/** @var \Magento\Framework\Escaper $escaper */
?>
<!-- Add your template code here. -->
{% endif %}
