<?php
/*
 * @copyright Copyright © ${commentsYear} ${CommentsCompanyName}. All rights reserved.
 * @author    ${commentsUserEmail}
 */
?>
<?php
use ${Vendorname}\${Modulename}\Block\${Block_name};
/** @var ${Block_name} $block  */
// Add your template code here ...
?>
<?php //@todo delete / replace this function with your implementation ?>
<h1><?php echo $block->escapeHtml($block->getSampleText()); ?></h1>








