{% if withBlock == true %}
{{ include(template_from_string(headerPHP)) }}
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \{{ vendorName|pascal }}\{{ moduleName|pascal }}\ViewModel\{{ name|pascal }} $viewModel */
$viewModel = $block->getViewModel();
?>
<div data-mage-init='<?= $escaper->escapeHtmlAttr($viewModel->getJsonConfig()) ?>'></div>
{% endif %}
