
MKDIR=mkdir
MV=mv
RM=rm
CD=cd

install-package:
	$(MKDIR) -p source/magento/lib/internal/codegen
	$(MV) ./module_tmp/.[!.]* ./module_tmp/..?* ./module_tmp/* ./source/magento/lib/internal/codegen
	$(RM) -d module_tmp
	$(DOCKER_COMPOSE_$(MODE_UPPERCASE)) exec --user www-data $(service) composer config repositories.codegen '{"type": "path", "url": "lib/internal/codegen"}'
	$(DOCKER_COMPOSE_$(MODE_UPPERCASE)) exec --user www-data $(service) composer require --dev orba/magento2-codegen:*
